version: '2'
services:
 jenkins:
  restart: always
  build: ./
  image: epicurus/jenkins
  container_name: jenkins
  networks:
   - net
  ports:
   - "380:8080"
  volumes:
   - /app/jenkins/:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
   - /sw/common/certs/:/certs
   - /usr/bin/docker:/usr/bin/docker
networks:
 net:
  external:
      name: epicurus-dev-tool-net
