version: '3'
services:
 sonar-proxy:
	restart: always
  image: nginx
  container_name: sonar-proxy
  ports:
   - "590:590"
  networks:
   - net
  volumes:
   - /app/sonar-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
   - /sw/common/certs:/etc/nginx/certs
networks:
 net:
  external:
      name: epicurus-dev-tool-net
