version: '3'
services:
 mysql:
  restart: always
  build: ./mysql/
  image: epicurus/mysql
  container_name: mysql
  networks:
   - net
  environment:
   - MYSQL_ROOT_PASSWORD=1!Mmysql
  volumes:
   - /app/mysql:/etc/mysql/conf.d
   # data dir
   - /db/mysql:/var/lib/mysql
 netdata:
  restart: always
  image: titpetric/netdata
  container_name: netdata
  networks:
   - net
  volumes:
   - /proc:/host/proc:ro
	 - /sys:/host/sys:ro
	 - /var/run/docker.sock:/var/run/docker.sock
  cap_add:
   - SYS_PTRACE
 netdata-proxy:
  restart: always
  image: nginx
  container_name: netdata-proxy
  ports:
   - "199:199"
  depends_on:
   - netdata
  networks:
   - net
  volumes:
   - /app/netdata-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
   - /sw/common/certs:/etc/nginx/certs
 jenkins:
  restart: always
  build: ./jenkins/
  image: epicurus/jenkins
  container_name: jenkins
  networks:
   - net
  ports:
   - "380:8080"
  volumes:
   - /app/jenkins/:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
   - /sw/common/certs/:/certs
   - /usr/bin/docker:/usr/bin/docker
 registry:
  restart: always
  image: registry:2
  container_name: registry
  networks:
   - net
  environment:
   - REGISTRY_AUTH=htpasswd
   - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
   - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
   - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/https/domain/cert.pem
   - REGISTRY_HTTP_TLS_KEY=/certs/https/domain/privkey.pem
  ports:
   - "450:5000"
  volumes:
   - /app/registry:/var/lib/registry
   - /sw/common/auth/registry:/auth
   - /sw/common/certs/:/certs
 sonarqube:
  restart: always
  image: sonarqube
  container_name: sonarqube
  ports:
   - "590:9000"
  depends_on:
   - mysql
  networks:
   - net
  environment:
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
   - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
  volumes:
   - /app/sonarqube/conf:/opt/sonarqube/conf
   - /app/sonarqube/extensions:/opt/sonarqube/extensions
   - /app/sonarqube/bundled-plugins:/opt/sonarqube/bundled-plugins
   - /app/sonarqube/data:/opt/sonarqube/data
   - /app/sonarqube/temp:/opt/sonarqube/temp
 sonar-proxy:
  image: nginx
  container_name: sonar-proxy
  ports:
   - "590:590"
  depends_on:
   - sonarqube
  networks:
   - net
  volumes:
   - /app/sonar-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
   - /sw/common/certs:/etc/nginx/certs
 gitlab-ce:
  restart: always
  image: gitlab/gitlab-ce
  container_name: gitlab-ce
  ports:
   - "780:780"
	 - "744:744"
   - "722:22"
  environment:
   ## setting another(https://docs.gitlab.com/omnibus/README.html)
   GITLAB_OMNIBUS_CONFIG: |
    external_url "https://<DOMAIN>:744"
    gitlab_url "https://<DOMAIN>:744"
    gitlab_rails['time_zone'] = "Asia/Seoul"
    gitlab_monitor['enable'] = false
    gitlab_rails['gitlab_shell_ssh_port'] = 722
    nginx['listen_port'] = 744
    nginx['redirect_http_to_https_port'] = 780
    nginx['redirect_http_to_https'] = true
    nginx['ssl_certificate'] = "/var/opt/gitlab/certs/fullchain1.pem"
    nginx['ssl_certificate_key'] = "/var/opt/gitlab/certs/privkey1.pem"
		## setting another mail server(https://docs.gitlab.com/omnibus/settings/smtp.html)
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = "smtp.gmail.com"
    gitlab_rails['smtp_port'] = 587
    gitlab_rails['smtp_user_name'] = "lkh5510@gmail.com"
    gitlab_rails['smtp_password'] = "xxxx"
    gitlab_rails['smtp_domain'] = "smtp.gmail.com"
    gitlab_rails['smtp_authentication'] = "login"
    gitlab_rails['smtp_enable_starttls_auto'] = true
    gitlab_rails['smtp_tls'] = false
    gitlab_rails['smtp_openssl_verify_mode'] = "peer"
  networks:
   - net
	volumes:
   - /app/gitlab/data:/var/opt/gitlab
   - /sw/common/certs:/var/opt/gitlab/certs
   - /app/gitlab/config:/etc/gitlab
   - /applog/gitlab:/var/log/gitlab
networks:
 net:
  external:
      name: epicurus-dev-tool-net
